name: pmd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 6 * * 1'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      

      - uses: pmd/pmd-github-action@v2
        id: pmd
        with:
          version: '6.55.0'
          sourcePath: 'src/main/java'
          rulesets: 'rulesets/java/quickstart.xml,ruleset.xml'
      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
