name: pmd

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '20 6 * * 1'

permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Run PMD
        uses: axians/mk-pmd-action@v3.0.0
        with:
          version: '6.55.0'              # Version de PMD à utiliser
          rulesets: 'java-basic'         # Règles PMD
          sourcePath: 'src/main/java'    # Dossier où se trouve votre code
          failThreshold: 5               # Seuil d'échec (5 violations)
          failOnError: true              # Fait échouer le job si le seuil est dépassé
          sarifOutputFile: 'pmd-report.sarif'
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'pmd-report.sarif'
